version: '3.7'
services:
  mongo:
    image: mongo
    ports:
        - 27017:27017
    container_name: mongodb

  mongo-test:
    image: mongo
    ports:
        - 27018:27017
    container_name: mongodb-test
    